name: Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint on PR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      statuses: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Typecheck
        run: pnpm typecheck
      - name: Run Linters
        run: pnpm lint
      - name: Tests
        run: pnpm test
      - name: Build
        run: pnpm build